services:
  app:
    image: todo-front-dev
    container_name: todo-front-dev 
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: . 
      dockerfile: dev.Dockerfile 
    volumes:
      - ./:/usr/src/app 
    ports:
      - 5173:5173
  debug-helper:
    image: busybox
    