services:
  app:
    image: blog-front-dev
    container_name: blog-front-dev 
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: . 
      dockerfile: dev.Dockerfile 
    volumes:
      - ./:/usr/src/app 
    ports:
      - 5173:5173
