services:
  app:
    image: blog-front-dev
    container_name: blog-frontend-dev 
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile 
    volumes:
      - ./frontend:/usr/src/app 
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app 
  server:
    image: blog-back-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3003:3003
    container_name: blog-backend-dev

