services:
  app:
    image: blog-frontend-production
    container_name: blog-frontend-production
    build:
      context: ./frontend
      dockerfile: Dockerfile 
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 5173:5173 
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: production-proxy
    depends_on:
      - app 
  server:
    image: blog-backend-production
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3003:3003
    container_name: blog-backend-production

